metrics:
  # List of metrics to run
  - AUC
label columns:
  # Label columns that are going to be evaluated
  - Cardiomegaly
  - Edema
  - Consolidation
  - Atelectasis
  - Pleural Effusion

# Common identifier column for labels and predictions
id column: Path