metrics:
  # List of metrics to run
  - AUC
  - F1
label columns:
  # Label columns that are going to be evaluated
  - Cardiomegaly
  - Edema
  - Consolidation
  - Atelectasis

# Common identifier column for labels and predictions
id column: Path